In [26]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from utilities3 import *

In [27]:
x=torch.rand(1,96,dtype=float).reshape(2,3,16)
print(x)
print(torch.std(x,0))

tensor([[[0.4198, 0.5385, 0.9359, 0.6843, 0.4963, 0.7030, 0.8310, 0.2056,
          0.4931, 0.5389, 0.7964, 0.7776, 0.8973, 0.1605, 0.9513, 0.0194],
         [0.7357, 0.0321, 0.6628, 0.8202, 0.4599, 0.8707, 0.9174, 0.1027,
          0.8560, 0.2628, 0.3131, 0.9774, 0.1574, 0.5358, 0.1196, 0.5126],
         [0.0755, 0.1678, 0.9048, 0.5787, 0.8180, 0.7074, 0.2156, 0.9227,
          0.7445, 0.8277, 0.4418, 0.6596, 0.5394, 0.2583, 0.8870, 0.2772]],

        [[0.2732, 0.6573, 0.1685, 0.7643, 0.2781, 0.0430, 0.3679, 0.2020,
          0.8840, 0.5996, 0.0193, 0.2427, 0.3979, 0.0462, 0.5231, 0.4667],
         [0.9846, 0.5610, 0.3517, 0.2085, 0.6878, 0.9548, 0.3078, 0.3525,
          0.9226, 0.1554, 0.2621, 0.5508, 0.4194, 0.3190, 0.1376, 0.9556],
         [0.0374, 0.1860, 0.6286, 0.0670, 0.8286, 0.1456, 0.4489, 0.0157,
          0.5356, 0.0386, 0.6092, 0.9275, 0.6353, 0.4367, 0.0388, 0.7099]]],
       dtype=torch.float64)
tensor([[0.1037, 0.0840, 0.5426, 0.0566, 0.1543, 0.4666, 0.3274, 0.0026, 0

In [28]:
x_normalizer = UnitGaussianNormalizer(x)

In [29]:
x = x_normalizer.encode(x)
x

tensor([[[ 0.7070, -0.7070,  0.7071, -0.7070,  0.7071,  0.7071,  0.7071,
           0.7044, -0.7071, -0.7069,  0.7071,  0.7071,  0.7071,  0.7070,
           0.7071, -0.7071],
         [-0.7071, -0.7071,  0.7071,  0.7071, -0.7071, -0.7070,  0.7071,
          -0.7071, -0.7070,  0.7070,  0.7069,  0.7071, -0.7071,  0.7071,
          -0.7066, -0.7071],
         [ 0.7068, -0.7066,  0.7071,  0.7071, -0.7062,  0.7071, -0.7071,
           0.7071,  0.7071,  0.7071, -0.7070, -0.7071, -0.7070, -0.7071,
           0.7071, -0.7071]],

        [[-0.7070,  0.7070, -0.7071,  0.7070, -0.7071, -0.7071, -0.7071,
          -0.7044,  0.7071,  0.7069, -0.7071, -0.7071, -0.7071, -0.7070,
          -0.7071,  0.7071],
         [ 0.7071,  0.7071, -0.7071, -0.7071,  0.7071,  0.7070, -0.7071,
           0.7071,  0.7070, -0.7070, -0.7069, -0.7071,  0.7071, -0.7071,
           0.7066,  0.7071],
         [-0.7068,  0.7066, -0.7071, -0.7071,  0.7062, -0.7071,  0.7071,
          -0.7071, -0.7071, -0.7071,  0.7070,  0.7

In [30]:
x=x_normalizer.decode(x)
print(x)

tensor([[[0.4198, 0.5385, 0.9359, 0.6843, 0.4963, 0.7030, 0.8310, 0.2056,
          0.4931, 0.5389, 0.7964, 0.7776, 0.8973, 0.1605, 0.9513, 0.0194],
         [0.7357, 0.0321, 0.6628, 0.8202, 0.4599, 0.8707, 0.9174, 0.1027,
          0.8560, 0.2628, 0.3131, 0.9774, 0.1574, 0.5358, 0.1196, 0.5126],
         [0.0755, 0.1678, 0.9048, 0.5787, 0.8180, 0.7074, 0.2156, 0.9227,
          0.7445, 0.8277, 0.4418, 0.6596, 0.5394, 0.2583, 0.8870, 0.2772]],

        [[0.2732, 0.6573, 0.1685, 0.7643, 0.2781, 0.0430, 0.3679, 0.2020,
          0.8840, 0.5996, 0.0193, 0.2427, 0.3979, 0.0462, 0.5231, 0.4667],
         [0.9846, 0.5610, 0.3517, 0.2085, 0.6878, 0.9548, 0.3078, 0.3525,
          0.9226, 0.1554, 0.2621, 0.5508, 0.4194, 0.3190, 0.1376, 0.9556],
         [0.0374, 0.1860, 0.6286, 0.0670, 0.8286, 0.1456, 0.4489, 0.0157,
          0.5356, 0.0386, 0.6092, 0.9275, 0.6353, 0.4367, 0.0388, 0.7099]]],
       dtype=torch.float64)


In [81]:
x=torch.rand([10,2,1024]).unsqueeze(dim=1)
conv1d_layer = nn.Conv2d(1,4,[2,8],bias = False)
y = conv1d_layer(x)

In [82]:
print(x.shape)
print(y.shape)
print(conv1d_layer.weight)

torch.Size([10, 1, 2, 1024])
torch.Size([10, 4, 1, 1017])
Parameter containing:
tensor([[[[ 0.1120,  0.1120, -0.2333,  0.1419, -0.0964,  0.1951,  0.1579,
           -0.2244],
          [ 0.0610,  0.0854, -0.0089,  0.0074, -0.2210,  0.1194,  0.0453,
           -0.0159]]],


        [[[ 0.0957, -0.0951,  0.2082, -0.1605, -0.1172,  0.1895,  0.1500,
           -0.2232],
          [ 0.1012, -0.0386, -0.0492, -0.0667,  0.0674,  0.0410, -0.1366,
            0.1445]]],


        [[[ 0.0515,  0.2248, -0.0968,  0.0802,  0.1117, -0.2204, -0.2407,
            0.0396],
          [ 0.0309,  0.1010, -0.1424,  0.2482,  0.1021, -0.0376, -0.1990,
            0.0706]]],


        [[[ 0.0827,  0.0436,  0.0342,  0.1553, -0.0519, -0.1019,  0.0344,
            0.2115],
          [-0.1966,  0.2191,  0.0641,  0.1305,  0.0582, -0.0091, -0.1939,
           -0.1711]]]], requires_grad=True)


In [63]:
weight = conv1d_layer.weight
print(x[0,:,0])
print(weight[0,:,0])
x[0,:,0] @ weight[0,:,0]


tensor([ 0., 10., 20., 30., 40.])
tensor([ 0.3941, -0.4271, -0.3221,  0.1499,  0.1428],
       grad_fn=<SelectBackward0>)


tensor(-0.5035, grad_fn=<DotBackward0>)

In [3]:
x = [1,2]
y=[3]
x*3

[1, 2, 1, 2, 1, 2]

In [2]:
x=(1,2)
y=(3)
x+y

TypeError: can only concatenate tuple (not "int") to tuple

In [6]:
[[] for i in range(10)]

[[], [], [], [], [], [], [], [], [], []]

In [26]:
x=torch.rand([10,1,2,1024])


In [30]:
conv1d_layer = nn.Conv2d(1,16,kernel_size=[2,5])
t = conv1d_layer(x)

In [31]:
print(t.shape)

torch.Size([10, 16, 1, 1020])


In [10]:
!nvidia-smi

Tue Oct  4 00:34:26 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   79C    P0    42W /  N/A |   3326MiB /  4096MiB |     74%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
torch.cuda.device('cuda:2')

In [35]:
class Permute(nn.Module):
    def __init__(self, *args):
        super().__init__()
        self.dim = args

    def forward(self, x):
        x = x.permute(dims = self.dim)
        return x

In [36]:
permute=Permute(0,2,1)
x=torch.arange(0,48).reshape(1,3,16)
x.shape

torch.Size([1, 3, 16])

In [37]:
x=permute(x)
x.shape

torch.Size([1, 16, 3])

In [19]:
x.permute(0,2,1).shape

torch.Size([1, 16, 3])

In [47]:
class convd_0(nn.Module):
    def __init__(self, out_channels, num_padding, num_kernel):
        super().__init__()
        self.out_channels = out_channels
        self.num_padding = num_padding
        self.num_kernel = num_kernel
        
    def forward(self, x):
        if len(x.shape) == 3:
            x = F.pad(x, self.num_padding).unsqueeze(dim=1)
#         elif len(x.shape) == 4:
#             x = F.pad(x, num_padding)
        convd_layer = nn.Conv2d(in_channels=1, out_channels=self.out_channels, 
                                kernel_size=self.num_kernel, device=x.device)
        convd_out = convd_layer(x)
        if convd_out.shape[2] == 1:
            convd_out = convd_out.squeeze(dim=2)
        return convd_out.to(x.device)

In [54]:
x=torch.arange(0,32,dtype=torch.float).reshape(1,2,16)
x=x

In [55]:
layer=convd_0(3,[1,1,0,0],[2,3])

In [56]:
y=layer(x)

In [57]:
y

tensor([[[ -0.1430,  -3.8581,  -4.1909,  -4.5236,  -4.8564,  -5.1891,  -5.5218,
           -5.8546,  -6.1873,  -6.5201,  -6.8528,  -7.1856,  -7.5183,  -7.8510,
           -8.1838, -13.8079],
         [ -3.8766,  -6.9053,  -7.3369,  -7.7685,  -8.2001,  -8.6317,  -9.0633,
           -9.4949,  -9.9265, -10.3581, -10.7897, -11.2213, -11.6528, -12.0844,
          -12.5160,  -6.7222],
         [  1.8091,   0.5432,   0.5419,   0.5406,   0.5394,   0.5381,   0.5368,
            0.5356,   0.5343,   0.5331,   0.5318,   0.5305,   0.5293,   0.5280,
            0.5267,  -2.1856]]], grad_fn=<SqueezeBackward1>)

In [2]:
x=[1,2,3,4]
x[0:-1]

[1, 2, 3]

In [12]:
x=torch.Tensor(x)

In [21]:
x.reshape(x.shape+torch.Tensor([1]))

TypeError: can only concatenate tuple (not "Tensor") to tuple

In [29]:
x.reshape([x.shape,1])

TypeError: reshape(): argument 'shape' (position 1) must be tuple of ints, not list